GET https://www.macapp.so/
Accept: application/json

###
GET https://www.yrxitong.com/
Accept: application/json

###
GET https://www.sharerw.com/
Accept: application/json

###
GET https://soft.macxf.com/
Accept: application/json

###
GET https://pc.qq.com/category/c0.html
Accept: application/json

###
GET https://www.52pojie.cn/forum.php
Accept: application/json

###
GET https://www.ghxi.com/
Accept: application/json

###
